### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by nikhilkattil** [sissaschool/xmlschema#112]
I was trying to validate an XML file which is around 395MB against an XSD and it failed with the below error:

C:\Personal\XML_Validation>python validateXML.py
Inside main method...!!!
Now calling the validatexml method...!!!
Inside the validatexml Function...!!!

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "validateXML.py", line 33, in <module>
    main()
  File "validateXML.py", line 27, in main
    validatexml()
  File "validateXML.py", line 12, in validatexml
    if my_xsd.is_valid(input_xml):
  File "C:\Personal\Python\lib\site-packages\xmlschema\validators\xsdbase.py", line 573, in is_valid
    error = next(self.iter_errors(source, use_defaults=use_defaults), None)
  File "C:\Personal\Python\lib\site-packages\xmlschema\validators\xsdbase.py", line 591, in iter_errors
    for result in self.iter_decode(source, path=path, use_defaults=use_defaults, namespaces=namespaces):
  File "C:\Personal\Python\lib\site-packages\xmlschema\validators\schema.py", line 982, in iter_decode
    namespaces.update(source.get_namespaces())
  File "C:\Personal\Python\lib\site-packages\xmlschema\resources.py", line 580, in get_namespaces
    for event, node in self.iterparse(resource, events=('start-ns',)):
MemoryError

**Comment by brunato** [comment]
This should be related to an open issue, see https://github.com/brunato/xmlschema/issues/102#issuecomment-475139011 .

**Comment by brunato** [comment]
With the new release v1.0.13 you can try the *lazy* validation mode available with validate API of the package:

 ```python
xmlschema.validate(source, schema, lazy=True)
```

It's an experimental feature that has still to be tested more, but can be useful for me if you check it with your data. 
Thanks

**Comment by brunato** [comment]
The *lazy* validation mode with v1.0.16 is considered stable and should resolve this memory usage issue.
