### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'iter_decode'

### ISSUE THREAD

**Issue by fnpeillat** [sissaschool/xmlschema#129]
Hi there, 

I was trying to get all the validation errors from `iter_errors` and I am getting this 
`AttributeError: 'NoneType' object has no attribute 'iter_decode'`

It only returns the first match.

```python
a = xsd.iter_errors(source=xml_response_from_file, schema_path=schema)

for err in a:
    print(err)
```

Full `Traceback`
```python
Traceback (most recent call last):
  File "/opt/pycharm-professional/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/opt/pycharm-professional/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-professional/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/opt/pycharm-professional/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-professional/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/fnp/QA/python-generic/xsd.py", line 22, in <module>
    for err in a:
  File "/home/fnp/python-venv/ota-venv/lib/python3.7/site-packages/xmlschema/validators/schema.py", line 1015, in iter_errors
    for result in xsd_element.iter_decode(elem, source=source, namespaces=namespaces,
AttributeError: 'NoneType' object has no attribute 'iter_decode'
```

Thanks for your time!

**Comment by fnpeillat** [comment]
The problem was that the incorrect `schema_path` was used. Sorry for the inconveniences.
