### ISSUE TITLE
Validating throws regex error

### ISSUE THREAD

**Issue by matkuki** [sissaschool/xmlschema#135]
Hi,

I'm on `Windows 10` with `Python 3.7.1` and `xmlschema` installed with `pip install xmlschema`.
When validating a `.xml` file like so (XML Schema 1.0):
```python
import xmlschema
xmlschema.validate("my_xml_file.xml", "my_xml_file.xsd")
```
this error is thrown:
```bash
Traceback (most recent call last):
  File "D:\PROJEKTI\TPV\XML\schema_manual_parse.py", line 418, in <module>
    functions.xml_schema_check(xml_filename)
  File "D:\PROJEKTI\TPV\XML\functions.py", line 19, in xml_schema_check
    return xmlschema.validate(filename, "coc-mitteilung.xsd")
  File "C:\Python37\lib\site-packages\xmlschema\documents.py", line 71, in validate
    schema.validate(source, path, schema_path, use_defaults, namespaces)
  File "C:\Python37\lib\site-packages\xmlschema\validators\schema.py", line 1088, in validate
    for error in self.iter_errors(source, path, schema_path, use_defaults, namespaces):
  File "C:\Python37\lib\site-packages\xmlschema\validators\schema.py", line 1150, in iter_errors
    xsd_element = self.get_element(elem.tag, schema_path, namespaces)
  File "C:\Python37\lib\site-packages\xmlschema\validators\schema.py", line 782, in get_element
    return self.find(tag)
  File "C:\Python37\lib\site-packages\xmlschema\xpath.py", line 233, in find
    default_namespace=self.xpath_default_namespace)
  File "C:\Python37\lib\site-packages\elementpath\xpath2_parser.py", line 178, in __init__
    self.tokenizer = create_tokenizer(self.symbol_table, XML_NCNAME_PATTERN)
  File "C:\Python37\lib\site-packages\elementpath\tdop_parser.py", line 93, in create_tokenizer
    return re.compile(pattern, re.VERBOSE)
  File "C:\Python37\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Python37\lib\sre_parse.py", line 819, in _parse
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 115 (line 3, column 9)
```
Any ideas?

Thanks

**Comment by brunato** [comment]
Hi,

I don't know. I tried the same (Win 10 + Python 3.7.1 + xmlschema) and all tests ran successful (except one related to a subprocess call...). Maybe something related to character set that broke the building of tokenizer pattern in `elementpath.tdop_parser module`.
Have you tried with a more recent version of Python 3.7?

**Comment by brunato** [comment]
Hi,
Try with v1.0.15 if you can. Without feedback I will assume that the problem is resolved.
Thank you
