### ISSUE TITLE
ElementPathTypeError after upgrading to >= 1.1.0

### ISSUE THREAD

**Issue by sammhho** [sissaschool/xmlschema#170]
The said error is thrown when creating a xmlschema object like this:
```python
xs = xmlschema.XMLSchema(str(args.xsd_path))
```

It happened only after upgrading to xmlschema 1.1.0, which in-turn needs elementpath~=1.4.0.
xmlschema==1.0.18 with elementpath==1.3.3 worked just fine.

I tried setting break-point outside of the if-clause on the working version,
```python
        if self.xsd_type is None:
            self.xsd_type = xsd_type
        elif self.xsd_type is not xsd_type:
            self.wrong_context_type("Multiple XSD type matching during static analysis")
        return xsd_type
```
but seems it never runs into that code block within `match_xsd_type` of elementpath/xpath_token.py around line 434.

The xsd used is an IEEE standard namely ip-xact, can be found here:
[https://www.accellera.org/xmlschema/ipxact/1685-2014](https://www.accellera.org/xmlschema/ipxact/1685-2014)
I used the `index.xsd` as input entry.

The stack trace:
```python
Exception has occurred: ElementPathTypeError
':' operator: [err:XPTY0004] Multiple XSD type matching during static analysis.
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/elementpath/xpath_token.py", line 657, in wrong_context_type
    raise self.error('XPTY0004', message)
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/elementpath/xpath_token.py", line 476, in match_xsd_type
    self.wrong_context_type("Multiple XSD type matching during static analysis")
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/elementpath/xpath1_parser.py", line 340, in select
    if self.match_xsd_type(schema_item, value) is not None:
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/elementpath/xpath1_parser.py", line 695, in select
    yield from self[1].select(context)
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/elementpath/xpath2_parser.py", line 364, in parse
    for _ in root_token.select(context=self.schema.get_context()):
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/xmlschema/xpath.py", line 261, in _xpath_parse
    return parser.parse(path)
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/xmlschema/xpath.py", line 295, in iterfind
    return self._xpath_parse(path, namespaces).select_results(context)
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/xmlschema/validators/identities.py", line 152, in iter_elements
    yield from self.parent.iterfind(self.selector.path, self.selector.namespaces)
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/xmlschema/validators/globals_.py", line 605, in <setcomp>
    constraint.elements = {
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/xmlschema/validators/globals_.py", line 605, in build
    constraint.elements = {
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/site-packages/xmlschema/validators/schema.py", line 423, in __init__
    self.maps.build()
  File "/Users/mhho/wrk/efx_IP/efx_ipmgr/efx_ipmgr/xml_.py", line 125, in xml_to_dict
    xs = xmlschema.XMLSchema(str(args.xsd_path))
  File "/Users/mhho/wrk/efx_IP/efx_ipmgr/efx_ipmgr/gen.py", line 590, in gen_wrapper
    xml_dict = xml_to_dict(args)
  File "/Users/mhho/wrk/efx_IP/efx_ipmgr/efx_ipmgr/__main__.py", line 52, in main
    func(args)
  File "/Users/mhho/wrk/efx_IP/efx_ipmgr/efx_ipmgr/__main__.py", line 56, in <module>
    main()
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mhho/anaconda3/envs/py38/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
```

It'd be great if someone can guide me to debug this or at least decide whether it's an issue with xmlschema or elementpath or the xsd i'm using.

Many thanks!

**Comment by brunato** [comment]
Hi,
this schema is tested in my local tests collection but using `component.xsd` as entry point:

```
#
# Accellera Systems Initiative
Accellera/1685-2009/component.xsd   # SPIRIT
Accellera/1685-2014/component.xsd   # IP-XACT
```
Using *index.xsd* it raises the same error that you shown.
 
This is a (bug/limitation) of *elementpath* like in general every error due to XPath processor. In this case the error is generated from an xpath expression of an *xs:selector* defined in the schemas (maybe an expression containing a wildcard or a union). I'll try to fix this for the next release of *elementpath*.

Best

**Comment by sammhho** [comment]
@brunato Thanks for the quick response! Looking forward to the fix.

**Comment by Thomasb81** [comment]
I got the same issue, but with a different code and options:

```
import xmlschema
my_schema = xmlschema.XMLSchema('ip-xact/1685-2009/index.xsd',validation='lax')
my_schema.find('//spirit:addressBlock')
```

The stack trace:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    elems = my_schema.find('//spirit:'+parentItemName)
  File "/home/tom/prog/wx-reader/venv/lib/python3.7/site-packages/xmlschema/xpath.py", line 270, in find
    return next(self._xpath_parse(path, namespaces).select_results(context), None)
  File "/home/tom/prog/wx-reader/venv/lib/python3.7/site-packages/xmlschema/xpath.py", line 259, in _xpath_parse
    return self._xpath_parser.parse(path)
  File "/home/tom/prog/wx-reader/venv/lib/python3.7/site-packages/elementpath/xpath2_parser.py", line 365, in parse
    for _ in root_token.select(context=self.schema.get_context()):
  File "/home/tom/prog/wx-reader/venv/lib/python3.7/site-packages/elementpath/xpath1_parser.py", line 753, in select
    for result in self[0].select(context):
  File "/home/tom/prog/wx-reader/venv/lib/python3.7/site-packages/elementpath/xpath1_parser.py", line 381, in select
    if self.match_xsd_type(schema_item, value) is not None:
  File "/home/tom/prog/wx-reader/venv/lib/python3.7/site-packages/elementpath/xpath_token.py", line 440, in match_xsd_type
    self.wrong_context_type("Multiple XSD type matching during static analysis")
  File "/home/tom/prog/wx-reader/venv/lib/python3.7/site-packages/elementpath/xpath_token.py", line 614, in wrong_context_type
    raise self.error('XPTY0004', message)

ElementPathTypeError: ':' operator: [err:XPTY0004] Multiple XSD type matching during static analysis.
```

Is `validation=lax` option still required ?

**Comment by brunato** [comment]
Published yesterday a new release of *elementpath* (v1.4.2). With this last release `1685-2009/index.xsd` seems to work:

```pycon
>>> import xmlschema
>>> my_schema = xmlschema.XMLSchema('1685-2009/index.xsd')
>>> my_schema.find('//spirit:addressBlock')
XsdElement(name='spirit:addressBlock', occurs=[1, 1])
```

The schema `1685-2014/index.xsd` seems to work with XSD 1.0 validator, but raises an error with XMLSchema11 validator that need to be checked for the next release of *xmlschema*:

```pycon
>>> my_schema = xmlschema.XMLSchema11('1685-2014/index.xsd')
Traceback (most recent call last):
...
xmlschema.validators.exceptions.XMLSchemaParseError: base Xsd11ComplexType(name='ipxact:unsignedBitExpression') is simple or has a simple content:

Schema:

  <xs:extension xmlns:xs="http://www.w3.org/2001/XMLSchema" base="ipxact:unsignedBitExpression">
      <xs:attribute name="resetTypeRef" type="xs:Name">
          <xs:annotation>
              <xs:documentation>Reference to a user defined resetType. Assumed to be HARD if not present.</xs:documentation>
          </xs:annotation>
      </xs:attribute>
      <xs:attributeGroup ref="ipxact:id.att" />
  </xs:extension>

Path: /xs:schema/xs:complexType[2]/xs:complexContent/xs:extension

Schema URL: file:///home/brunato/Development/projects/extra-schemas/Accellera/1685-2014/signalDrivers.xsd

Origin URL: file:///home/brunato/Development/projects/extra-schemas/Accellera/1685-2014/index.xsd
>>> 

```

**Comment by Thomasb81** [comment]
Those schema should comply with schema 1.0. But schema1.1 is a super set of schema1.0, right ?

Also xmlspy is reporting warning message when loading the file (I have no idea of what it means):
```
File 1685-2014\schema\index.xsd is valid but contains one or more warnings.
The XPath 'ipxact:busInterfaces/ipxact:busInterface/ipxact:slave/ipxact:bridge' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:selector
Details
The XPath 'ipxact:busInterfaces/ipxact:busInterface/ipxact:slave/ipxact:bridge' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath '@masterRef' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@masterRef' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath '@ipxact:state' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@ipxact:state' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath '@ipxact:state' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@ipxact:state' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath 'ipxact:model/ipxact:views/ipxact:view/ipxact:whiteboxElementRefs/ipxact:whiteboxElementRef' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:selector
Details
The XPath 'ipxact:model/ipxact:views/ipxact:view/ipxact:whiteboxElementRefs/ipxact:whiteboxElementRef' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath '@name' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@name' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath 'ipxact:adHocConnections/ipxact:adHocConnection/ipxact:internalPortReference' does not point to any schema element or attribute within the content of element 'ipxact:design'.
Warning location: xs:schema / xs:element / xs:keyref / xs:selector
Details
The XPath 'ipxact:adHocConnections/ipxact:adHocConnection/ipxact:internalPortReference' does not point to any schema element or attribute within the content of element 'ipxact:design'.
The XPath '@componentRef' does not point to any schema element or attribute within the content of element 'ipxact:design'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@componentRef' does not point to any schema element or attribute within the content of element 'ipxact:design'.
The XPath 'ipxact:interconnectionConfiguration/ipxact:abstractors/ipxact:abstractor' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:selector
Details
The XPath 'ipxact:interconnectionConfiguration/ipxact:abstractors/ipxact:abstractor' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath 'ipxact:instanceName' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath 'ipxact:instanceName' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath 'ipxact:generatorChainConfiguration/ipxact:generatorChainRef' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:selector
Details
The XPath 'ipxact:generatorChainConfiguration/ipxact:generatorChainRef' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@vendor' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath '@vendor' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@library' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath '@library' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@name' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath '@name' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@version' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath '@version' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath 'ipxact:interconnectionConfiguration/ipxact:abstractors/ipxact:abstractor' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:selector
Details
The XPath 'ipxact:interconnectionConfiguration/ipxact:abstractors/ipxact:abstractor' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath 'ipxact:instanceName' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath 'ipxact:instanceName' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath 'ipxact:generatorChainConfiguration/ipxact:generatorChainRef' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:selector
Details
The XPath 'ipxact:generatorChainConfiguration/ipxact:generatorChainRef' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@vendor' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath '@vendor' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@library' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath '@library' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@name' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath '@name' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@version' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
Warning location: xs:schema / xs:element / xs:key / xs:field
Details
The XPath '@version' does not point to any schema element or attribute within the content of element 'ipxact:designConfiguration'.
The XPath '@ipxact:state' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@ipxact:state' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath 'ipxact:busInterfaces/ipxact:busInterface/ipxact:slave/ipxact:bridge' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:selector
Details
The XPath 'ipxact:busInterfaces/ipxact:busInterface/ipxact:slave/ipxact:bridge' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath '@masterRef' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@masterRef' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath 'ipxact:model/ipxact:views/ipxact:view/ipxact:whiteboxElementRefs/ipxact:whiteboxElementRef' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:selector
Details
The XPath 'ipxact:model/ipxact:views/ipxact:view/ipxact:whiteboxElementRefs/ipxact:whiteboxElementRef' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath '@name' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@name' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath '@ipxact:state' does not point to any schema element or attribute within the content of element 'ipxact:component'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@ipxact:state' does not point to any schema element or attribute within the content of element 'ipxact:component'.
The XPath 'ipxact:adHocConnections/ipxact:adHocConnection/ipxact:internalPortReference' does not point to any schema element or attribute within the content of element 'ipxact:design'.
Warning location: xs:schema / xs:element / xs:keyref / xs:selector
Details
The XPath 'ipxact:adHocConnections/ipxact:adHocConnection/ipxact:internalPortReference' does not point to any schema element or attribute within the content of element 'ipxact:design'.
The XPath '@componentRef' does not point to any schema element or attribute within the content of element 'ipxact:design'.
Warning location: xs:schema / xs:element / xs:keyref / xs:field
Details
The XPath '@componentRef' does not point to any schema element or attribute within the content of element 'ipxact:design'.
```

**Comment by brunato** [comment]
In general an XSD 1.0 schema should be accepted also by an XSD 1.1 validator.

These xmlspy's errors seems to be some XPath dangling references (the schema is still valid anyway).

For *xmlschema* it should be a typo in an additional check made by `XMLSchema11` validator. This is also a TODO for my test class for schemas (made by a test factory on XSD testfiles set). I will add more tests with `XMLSchema11` validator for the next release.

Thanks

**Comment by brunato** [comment]
**Update on XSD 1.0 and XSD 1.1 compatibility**

In general a schema valid with XSD 1.0 is also valid in XSD 1.1 but in this case the schema has a complex content extension, permitted in XSD 1.0 but not allowed in XSD 1.1.

These are the reference sections of the two standards:

  * **XSD 1.0**: https://www.w3.org/TR/xmlschema-1/#cos-ct-extends
  * **XSD 1.1**: https://www.w3.org/TR/2012/REC-xmlschema11-1-20120405/#sec-cos-ct-extends

Also a the file [particlesZ031.xsd](https://github.com/w3c/xsdtests/blob/281a411222ce02ee6061b33af17b052a490d7e24/msData/particles/particlesZ031.xsd) of the W3C XSD 1.1 test suite, that is a similar case,  is valid in XSD 1.0 and invalid with XSD 1.1 (refer to https://www.w3.org/Bugs/Public/show_bug.cgi?id=15629).

Anyway I have added a check also with XSD 1.1 for each valid schema tested with XSD 1.0. Excluding this kind of error my schema cases valid in XSD 1.0 are also valid with XSD 1.1 validator.

**Comment by brunato** [comment]
[IP-XACT schema 1685-2014](http://www.accellera.org/XMLSchema/IPXACT/1685-2014) seems to be not fully compliant with XSD 1.1. Process it with validation='lax' (it's parsed with just one error, an error related with the previous comment).
