### ISSUE TITLE
pip install xmlschema result in error for python 2.7 and pip 20

### ISSUE THREAD

**Issue by vicding-mi** [sissaschool/xmlschema#181]
When running `pip instal xmlschema`, there seems to be an compatibility issue with python 2.7

The error message as below
```
 File "xmlschema/exceptions.py", line 13, in <module>
        from urllib.error import URLError
    ImportError: No module named error
```

Full error below
```
ckan@6b8ddb0e6c9b:/$ ckan-pip install xmlschema
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting xmlschema
  Downloading xmlschema-1.1.2.tar.gz (297 kB)
     |################################| 297 kB 1.3 MB/s 
Collecting elementpath~=1.4.0
  Downloading elementpath-1.4.3.tar.gz (117 kB)
     |################################| 117 kB 10.5 MB/s 
Installing collected packages: elementpath, xmlschema
    Running setup.py install for elementpath ... done
    Running setup.py install for xmlschema ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/lib/ckan/venv/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-YphUNv/xmlschema/setup.py'"'"'; __file__='"'"'/tmp/pip-install-YphUNv/xmlschema/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-haQedT/install-record.txt --single-version-externally-managed --compile --install-headers /usr/lib/ckan/venv/include/site/python2.7/xmlschema
         cwd: /tmp/pip-install-YphUNv/xmlschema/
    Complete output (270 lines):
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extra_require'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/exceptions.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/__init__.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/etree.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/helpers.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/qnames.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/regex.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/codepoints.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/xpath.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/limits.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/resources.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/documents.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/namespaces.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/compat.py -> build/lib.linux-x86_64-2.7/xmlschema
    copying xmlschema/converters.py -> build/lib.linux-x86_64-2.7/xmlschema
    running egg_info
    writing requirements to xmlschema.egg-info/requires.txt
    writing xmlschema.egg-info/PKG-INFO
    writing top-level names to xmlschema.egg-info/top_level.txt
    writing dependency_links to xmlschema.egg-info/dependency_links.txt
    reading manifest file 'xmlschema.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    writing manifest file 'xmlschema.egg-info/SOURCES.txt'
    copying xmlschema/unicode_categories.json -> build/lib.linux-x86_64-2.7/xmlschema
    creating build/lib.linux-x86_64-2.7/xmlschema/testing
    copying xmlschema/testing/__init__.py -> build/lib.linux-x86_64-2.7/xmlschema/testing
    copying xmlschema/testing/builders.py -> build/lib.linux-x86_64-2.7/xmlschema/testing
    copying xmlschema/testing/case_class.py -> build/lib.linux-x86_64-2.7/xmlschema/testing
    copying xmlschema/testing/factory.py -> build/lib.linux-x86_64-2.7/xmlschema/testing
    copying xmlschema/testing/observers.py -> build/lib.linux-x86_64-2.7/xmlschema/testing
    creating build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/__init__.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/assertions.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/attributes.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/builtins.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/complex_types.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/elements.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/exceptions.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/facets.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/global_maps.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/groups.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/identities.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/models.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/notations.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/schema.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/simple_types.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/wildcards.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    copying xmlschema/validators/xsdbase.py -> build/lib.linux-x86_64-2.7/xmlschema/validators
    creating build/lib.linux-x86_64-2.7/xmlschema/validators/schemas
    copying xmlschema/validators/schemas/XMLSchema-hasFacetAndProperty_minimal.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas
    copying xmlschema/validators/schemas/XMLSchema-instance_minimal.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas
    copying xmlschema/validators/schemas/XMLSchema-versioning_minimal.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas
    copying xmlschema/validators/schemas/xhtml1-strict.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas
    copying xmlschema/validators/schemas/xlink.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas
    copying xmlschema/validators/schemas/xml_minimal.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas
    creating build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.0
    copying xmlschema/validators/schemas/XSD_1.0/XMLSchema.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.0
    copying xmlschema/validators/schemas/XSD_1.0/datatypes.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.0
    creating build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.1
    copying xmlschema/validators/schemas/XSD_1.1/XMLSchema.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.1
    copying xmlschema/validators/schemas/XSD_1.1/datatypes.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.1
    copying xmlschema/validators/schemas/XSD_1.1/xsd11-extra.xsd -> build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.1
    running install_lib
    creating /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/exceptions.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/unicode_categories.json -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    creating /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing
    copying build/lib.linux-x86_64-2.7/xmlschema/testing/observers.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing
    copying build/lib.linux-x86_64-2.7/xmlschema/testing/__init__.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing
    copying build/lib.linux-x86_64-2.7/xmlschema/testing/case_class.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing
    copying build/lib.linux-x86_64-2.7/xmlschema/testing/builders.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing
    copying build/lib.linux-x86_64-2.7/xmlschema/testing/factory.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing
    creating /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/exceptions.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/groups.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/global_maps.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/builtins.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/attributes.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/__init__.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/simple_types.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/models.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    creating /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XMLSchema-hasFacetAndProperty_minimal.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas
    creating /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas/XSD_1.1
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.1/datatypes.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas/XSD_1.1
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.1/xsd11-extra.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas/XSD_1.1
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.1/XMLSchema.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas/XSD_1.1
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/xlink.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/xml_minimal.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XMLSchema-versioning_minimal.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XMLSchema-instance_minimal.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas
    creating /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas/XSD_1.0
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.0/datatypes.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas/XSD_1.0
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/XSD_1.0/XMLSchema.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas/XSD_1.0
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schemas/xhtml1-strict.xsd -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schemas
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/identities.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/wildcards.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/facets.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/notations.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/complex_types.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/xsdbase.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/elements.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/assertions.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/validators/schema.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators
    copying build/lib.linux-x86_64-2.7/xmlschema/__init__.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/etree.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/helpers.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/qnames.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/regex.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/codepoints.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/xpath.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/limits.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/resources.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/documents.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/namespaces.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/compat.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    copying build/lib.linux-x86_64-2.7/xmlschema/converters.py -> /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/exceptions.py to exceptions.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing/observers.py to observers.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing/__init__.py to __init__.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing/case_class.py to case_class.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing/builders.py to builders.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/testing/factory.py to factory.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/exceptions.py to exceptions.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/groups.py to groups.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/groups.py", line 297
        yield from item.iter_components(xsd_classes)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/global_maps.py to global_maps.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/global_maps.py", line 358
        yield from xsd_global.iter_components(xsd_classes)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/builtins.py to builtins.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/attributes.py to attributes.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/attributes.py", line 215
        yield from self.type.iter_components(xsd_classes)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/__init__.py to __init__.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/simple_types.py to simple_types.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/simple_types.py", line 384
        yield from self.patterns(obj)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/models.py to models.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/models.py", line 185
        yield from item.iter_model(depth + 1)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/identities.py to identities.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/identities.py", line 152
        yield from self.parent.iterfind(self.selector.path, self.selector.namespaces)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/wildcards.py to wildcards.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/wildcards.py", line 450
        yield from xsd_element.iter_decode(elem, validation, **kwargs)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/facets.py to facets.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/facets.py", line 46
        yield from self.validator(value)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/notations.py to notations.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/complex_types.py to complex_types.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/complex_types.py", line 556
        yield from self.attributes.iter_components(xsd_classes)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/xsdbase.py to xsdbase.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/elements.py to elements.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/elements.py", line 109
        yield from self.type.content_type.iter_elements()
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/assertions.py to assertions.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/assertions.py", line 122
        yield from self.parent.content_type.iter_elements()
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schema.py to schema.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/validators/schema.py", line 141
        class XMLSchemaBase(XsdValidator, ValidationMixin, ElementPathMixin, metaclass=XMLSchemaMeta):
                                                                                      ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/__init__.py to __init__.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/etree.py to etree.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/etree.py", line 237
        yield from etree_iterpath(child, tag, child_path, namespaces)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/helpers.py to helpers.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/helpers.py", line 139
        yield from iter_nested_items(v, dict_class, list_class)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/qnames.py to qnames.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/regex.py to regex.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/codepoints.py to codepoints.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/codepoints.py", line 180
        yield from range(ord(char) + 1, ord(end_char) + 1)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/xpath.py to xpath.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/xpath.py", line 65
        yield from safe_iter_context(context)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/limits.py to limits.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/resources.py to resources.pyc
      File "/usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/resources.py", line 683
        yield from self._root.iter(tag)
                 ^
    SyntaxError: invalid syntax
    
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/documents.py to documents.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/namespaces.py to namespaces.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/compat.py to compat.pyc
    byte-compiling /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema/converters.py to converters.pyc
    running install_egg_info
    Copying xmlschema.egg-info to /usr/lib/ckan/venv/lib/python2.7/site-packages/xmlschema-1.1.2-py2.7.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-record-haQedT/install-record.txt'
    Post-install: create Unicode categories JSON file
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-YphUNv/xmlschema/setup.py", line 73, in <module>
        'Topic :: Software Development :: Libraries'
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-YphUNv/xmlschema/setup.py", line 34, in run
        codepoints_module = importlib.import_module('xmlschema.codepoints')
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "xmlschema/__init__.py", line 12, in <module>
        from .exceptions import XMLSchemaException, XMLSchemaRegexError, XMLSchemaURLError, \
      File "xmlschema/exceptions.py", line 13, in <module>
        from urllib.error import URLError
    ImportError: No module named error
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/lib/ckan/venv/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-YphUNv/xmlschema/setup.py'"'"'; __file__='"'"'/tmp/pip-install-YphUNv/xmlschema/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-haQedT/install-record.txt --single-version-externally-managed --compile --install-headers /usr/lib/ckan/venv/include/site/python2.7/xmlschema Check the logs for full command output.
```

**Comment by brunato** [comment]
Hi,

I'm sorry but xmlschema > 1.1.0 is not compatible with Python 2.7. The last release compatible with Python 2 is the release v1.0.18. To install this release you have to use the command:

```bash
pip install xmlschema==1.0.18
```

**Comment by vicding-mi** [comment]
Ahhh, ic. Many thanks! will close the ticket.
