### ISSUE TITLE
xsd:enumeration not handled correctly?

### ISSUE THREAD

**Issue by gboor** [sissaschool/xmlschema#202]
I have a complex XSD schema consisting of multiple files. I've attached it for reference.

The schema has multiple values with xsd:enumeration and while loading the main XSD, schema/wgedi/errp/urn-entsoe-eu-wgedi-errp-plannedresourcescheduledocument-5-0.xsd (which loads all the other ones), it throws a validation error. This is before I try to validate any XML.

Error;
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    main()
  File "main.py", line 5, in main
    my_schema = xmlschema.XMLSchema('schema/wgedi/errp/urn-entsoe-eu-wgedi-errp-plannedresourcescheduledocument-5-0.xsd')
  File ".\venv\lib\site-packages\xmlschema\validators\schema.py", line 463, in __init__
    self.maps.build()
  File ".\venv\lib\site-packages\xmlschema\validators\global_maps.py", line 574, in build
    self.lookup_type(qname)
  File ".\venv\lib\site-packages\xmlschema\validators\global_maps.py", line 253, in lookup_type
    return lookup_type(qname, self.types, self.validator.BUILDERS_MAP)
  File ".\venv\lib\site-packages\xmlschema\validators\global_maps.py", line 152, in lookup
    global_map[qname] = factory_or_class(elem, schema, parent=None)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 61, in xsd_simple_type_factory
    xsd_type = schema.BUILDERS.union_class(child, schema, parent)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 879, in __init__
    super(XsdUnion, self).__init__(elem, schema, parent, name, facets=None)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 114, in __init__
    super(XsdSimpleType, self).__init__(elem, schema, parent, name)
  File ".\venv\lib\site-packages\xmlschema\validators\xsdbase.py", line 237, in __init__
    self.elem = elem
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 900, in __setattr__
    super(XsdUnion, self).__setattr__(name, value)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 119, in __setattr__
    super(XsdSimpleType, self).__setattr__(name, value)
  File ".\venv\lib\site-packages\xmlschema\validators\xsdbase.py", line 253, in __setattr__
    self._parse()
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 923, in _parse
    mt = self.maps.lookup_type(type_qname)
  File ".\venv\lib\site-packages\xmlschema\validators\global_maps.py", line 253, in lookup_type
    return lookup_type(qname, self.types, self.validator.BUILDERS_MAP)
  File ".\venv\lib\site-packages\xmlschema\validators\global_maps.py", line 152, in lookup
    global_map[qname] = factory_or_class(elem, schema, parent=None)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 57, in xsd_simple_type_factory
    xsd_type = schema.BUILDERS.restriction_class(child, schema, parent)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 448, in __init__
    super(XsdAtomic, self).__init__(elem, schema, parent, name, facets)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 114, in __init__
    super(XsdSimpleType, self).__init__(elem, schema, parent, name)
  File ".\venv\lib\site-packages\xmlschema\validators\xsdbase.py", line 237, in __init__
    self.elem = elem
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 1084, in __setattr__
    super(XsdAtomicRestriction, self).__setattr__(name, value)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 459, in __setattr__
    super(XsdAtomic, self).__setattr__(name, value)
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 119, in __setattr__
    super(XsdSimpleType, self).__setattr__(name, value)
  File ".\venv\lib\site-packages\xmlschema\validators\xsdbase.py", line 253, in __setattr__
    self._parse()
  File ".\venv\lib\site-packages\xmlschema\validators\simple_types.py", line 1194, in _parse
    facets[child.tag] = facet_class(child, self.schema, self, base_type)
  File ".\venv\lib\site-packages\xmlschema\validators\facets.py", line 566, in __init__
    XsdFacet.__init__(self, elem, schema, parent, base_type)
  File ".\venv\lib\site-packages\xmlschema\validators\facets.py", line 40, in __init__
    super(XsdFacet, self).__init__(elem, schema, parent)
  File ".\venv\lib\site-packages\xmlschema\validators\xsdbase.py", line 237, in __init__
    self.elem = elem
  File ".\venv\lib\site-packages\xmlschema\validators\xsdbase.py", line 253, in __setattr__
    self._parse()
  File ".\venv\lib\site-packages\xmlschema\validators\facets.py", line 571, in _parse
    self.enumeration = [self._parse_value(self.elem)]
  File ".\venv\lib\site-packages\xmlschema\validators\facets.py", line 575, in _parse_value
    value = self.base_type.decode(elem.attrib['value'], namespaces=self.schema.namespaces)
  File ".\venv\lib\site-packages\xmlschema\validators\xsdbase.py", line 818, in decode
    raise result
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating 'A01' with XsdEnumerationFacets(['8716867000016']):

Reason: invalid value 'A01', it must be one of ['8716867000016']

Schema:

  <xsd:enumeration xmlns:xsd="http://www.w3.org/2001/XMLSchema" value="8716867000016" />
```

It seems like the parser, after reading the first xsd:enumeration, tries to validate all other ones against that?

These are industrial XSDs by ENTSO-E and are widely in use. I don't think it's an issue with the XSD files.
[entso-e.zip](https://github.com/sissaschool/xmlschema/files/5149862/entso-e.zip)

**Comment by brunato** [comment]
Hi,

it seems to be a problem with an invalid enumeration restriction in the schema.
To have a confirmation I've downloaded the archive and tested the schema with lxml:

```pycon
>>> import lxml.etree as et
>>> xs = et.parse('schema/wgedi/errp/urn-entsoe-eu-wgedi-errp-plannedresourcescheduledocument-5-0.xsd')
>>> schema = et.XMLSchema(xs.getroot())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}enumeration': [facet 'enumeration'] The value 'EUR' is not an element of the set {'BAM'}., line 48
```
the error message is different but the problem is the same.

Also reproducing the issue with the involved types with a sample schema:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:simpleType name="LocalEnergyProductType">
        <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="8716867000016" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="LocalRestrictedEnergyProductType">
        <xs:restriction base="LocalEnergyProductType">
	    <xs:enumeration value="A01"/>
	</xs:restriction>
    </xs:simpleType>

</xs:schema>
```
the schema remains invalid with lxml:

```
>>> import lxml.etree as et
>>> xs = et.parse('issue_202.xsd')
>>> schema = et.XMLSchema(xs.getroot())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}enumeration': [facet 'enumeration'] The value 'A01' is not an element of the set {'8716867000016'}., line 12
```

and also a Xerces on-line validator reports that it has an invalid restriction:

```
[Error] issue_202.xsd:20:55:enumeration-valid-restriction: Enumeration value 'A01' is not in the value space of the base type, LocalEnergyProductType.
```

Maybe the schema could be outdated and replaced by valid versions. If you post a link of the XSD resources I can check.

**Comment by brunato** [comment]
Looking on ENTSO-E site i found a [package of schemas](https://www.entsoe.eu/Documents/EDI/Library/CIM_xsd_package.zip) referenced by the page https://www.entsoe.eu/publications/electronic-data-interchange-edi-library/. With these schemas all seems fine.

**Comment by gboor** [comment]
The XSDs I have came from TenneT (the Dutch TSO) and are apparently a mix of various ENTSO-E XSDs and their own additions. Their XML tool does validate it all correctly, but you are right; no other XML tools seem to.

I will take this up with them, sorry for the spam; since it worked in their test env I assumed it was a library error, but it looks like they are at fault.
