### ISSUE TITLE
Can't parse the XMLSchema Document

### ISSUE THREAD

**Issue by fragwuerdig** [sissaschool/xmlschema#203]
I tried to parse the XMLSchema schema document: https://www.w3.org/2012/04/XMLSchema.xsd using the following code snipped using Python3.7:

```
import xmlschema
xs = xmlschema.XMLSchema("XMLSchema.xsd")
```

I got the following exception

```
Traceback (most recent call last):
  File "unmarsh.py", line 2, in <module>
    xs = xmlschema.XMLSchema('XMLSchema.xsd')
  File "/home/mcs/.local/lib/python3.7/site-packages/xmlschema/validators/schema.py", line 463, in __init__
    self.maps.build()
  File "/home/mcs/.local/lib/python3.7/site-packages/xmlschema/validators/global_maps.py", line 590, in build
    self.check(filter(lambda x: x.meta_schema is not None, not_built_schemas), self.validation)
  File "/home/mcs/.local/lib/python3.7/site-packages/xmlschema/validators/global_maps.py", line 637, in check
    "of the base type group", validation=validation)
  File "/home/mcs/.local/lib/python3.7/site-packages/xmlschema/validators/xsdbase.py", line 175, in parse_error
    raise error
xmlschema.validators.exceptions.XMLSchemaParseError: the derived group is an illegal restriction of the base type group:
 
Schema:
 
  <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema" name="all">
    <xs:annotation>
      <xs:documentation>
   Only elements allowed inside</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:restriction base="xs:explicitGroup">
        <xs:group ref="xs:allModel" />
        <xs:attribute default="1" name="minOccurs" use="optional">
          <xs:simpleType>
            <xs:restriction base="xs:nonNegativeInteger">
              <xs:enumeration value="0" />
              <xs:enumeration value="1" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute default="1" name="maxOccurs" use="optional">
          <xs:simpleType>
            <xs:restriction base="xs:allNNI">
              <xs:enumeration value="1" />
   ...
   ...
  </xs:complexType>
 
Path: /xs:schema/xs:complexType[24]
 
Schema URL: file:///home/mcs/XMLSchema.xsd
```

Expected behaviour: Should parse flawlessly, because XMLSchema.xsd is a well formed schema document.

**Comment by fragwuerdig** [comment]
Can be tested using lxml library:

```
import lxml
g = open('XMLSchema.xsd')
doc = etree.parse(g)
schema = etree.XMLSchema(doc)
print(schema.validate(doc))
```

prints:

`True`

**Comment by brunato** [comment]
Hi,

this is the XSD 1.1 meta-schema and is validated by XSD 1.1 validator:

```pycon
>>> import xmlschema
>>> schema = xmlschema.XMLSchema11("https://www.w3.org/2012/04/XMLSchema.xsd")
>>> schema
XMLSchema11(name='XMLSchema.xsd', namespace='http://www.w3.org/2001/XMLSchema')
```

the XSD 1.0 validator can parse and validate the XSD 1.0 meta-schema:

```pycon
>>> schema = xmlschema.XMLSchema("https://www.w3.org/2001/XMLSchema.xsd", defuse='never')
>>> schema
XMLSchema10(name='XMLSchema.xsd', namespace='http://www.w3.org/2001/XMLSchema')
```

so the point is if the complexType "xs:all" is an illegal restriction of "xs:explicitGroup" in XSD 1.0 and legal in XSD 1.1.

**Comment by brunato** [comment]
More precisely the restriction validation fails because the model group "allModel":

```xsd
  <xs:group name="allModel">
    <xs:sequence>
      <xs:element ref="xs:annotation" minOccurs="0"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>This choice with min/max is here to
                          avoid a pblm with the Elt:All/Choice/Seq
                          Particle derivation constraint</xs:documentation>
        </xs:annotation>
        <xs:element name="element" type="xs:localElement"/>
        <xs:element ref="xs:any"/>
        <xs:element name="group">
          <xs:complexType>
            <xs:complexContent>
              <xs:restriction base="xs:groupRef">
                <xs:sequence>
                  <xs:element ref="xs:annotation" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="minOccurs" fixed="1" type="xs:nonNegativeInteger"/>
                <xs:attribute name="maxOccurs" fixed="1" type="xs:nonNegativeInteger"/>
              </xs:restriction>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:group>
```

is not a valid restriction of model group "nestedParticle" in XSD 1.0 (but it's a valid restriction in XSD 1.1):

```xsd
  <xs:group name="nestedParticle">
    <xs:choice>
      <xs:element name="element" type="xs:localElement"/>
      <xs:element name="group" type="xs:groupRef"/>
      
      <xs:element ref="xs:choice"/>
      <xs:element ref="xs:sequence"/>
      <xs:element ref="xs:any"/>
    </xs:choice>
  </xs:group>
```

This is true because in XSD 1.0 also a choice restriction has to respect the order of the declared items, in XSD 1.1 this constraint has been relaxed and the order is not compulsory.

**Comment by brunato** [comment]
So making a simple schema containing a complexType restriction of equivalent models (in terms of choice model restriction):

```xsd
<?xml version='1.0'?>
<!-- issue_203.xsd -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="root" type="restrictedModel"/>

    <xs:complexType name="baseModel">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="elem1"/>
            <xs:element name="elem2"/>
            <xs:element name="elem3"/>
            <xs:element name="elem4"/>
            <xs:element name="elem5"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="restrictedModel">
        <xs:complexContent>
            <xs:restriction base="baseModel">
                <xs:choice>
                    <xs:element name="elem1"/>
                    <xs:element name="elem5"/>
                    <xs:element name="elem2"/>
                </xs:choice>
            </xs:restriction>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>
```
and a valid instance:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- issue_203.xml -->
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="issue_203.xsd">
    <elem1/>
</root>
```

**Comment by brunato** [comment]
The previous schema is clearly invalid with XSD 1.0 but is valid in XSD 1.1 (also checked for XSD 1.0 with a couple of on-line validators and for both with Xerces). The errors reported by Xerces with XSD 1.0 are:

```
[Error] issue_203.xsd:17:44:rcase-RecurseLax.2: There is not a complete functional mapping between the particles.
[Error] issue_203.xsd:17:44:derivation-ok-restriction.5.4.2: Error for type 'restrictedModel'. The particle of the type is not a valid restriction of the particle of the base.
```

But with lxml the schema is considered valid with its XSD 1.0 validator, and then the instance:

```pycon
>>> import lxml.etree as et
>>> schema = et.XMLSchema(et.parse("issue_203.xsd"))
>>> schema.validate(et.parse("issue_203.xml"))
True
```

So for controversial cases I think is better to not ever count only on lxml's XSD 1.0 validator and try also other validation tools.

**Comment by brunato** [comment]
The XSD 1.1 meta-schema lacks of some declarations that i had integrated with an additional schema (see the additional base schema *"xsd11-extra.xsd"*) so the error that you've reported can be also an oversight. 

In fact changing the order of xs:choice items in the model "allModel" (moving `<xs:element ref="xs:any"/>` at last position) the schema became valid also with XSD 1.0.

Best Regards

**Comment by fragwuerdig** [comment]
Okay, using a XMLSchema11 instance I had no problems parsing and validating the Metaschema. I was not aware of the different schema versions. Thanks a lot! Bets Regards.
