### ISSUE TITLE
Python 3.10 regression in 1.6.3: TypeError: PurePath._from_parts() got an unexpected keyword argument 'init'

### ISSUE THREAD

**Issue by mgorny** [sissaschool/xmlschema#251]
Seems like using some private API to me.

```pytb
$ tox -e py310
GLOB sdist-make: /tmp/xmlschema/setup.py
py310 create: /home/mgorny/.tox/xmlschema/py310
py310 installdeps: elementpath>=2.2.2, <3.0.0, lxml, jinja2
py310 inst: /home/mgorny/.tox/xmlschema/.tmp/package/1/xmlschema-1.6.3.zip
py310 installed: elementpath==2.2.2,Jinja2==3.0.1,lxml==4.6.3,MarkupSafe==2.0.1,xmlschema @ file:///home/mgorny/.tox/xmlschema/.tmp/package/1/xmlschema-1.6.3.zip
py310 run-test-pre: PYTHONHASHSEED='2645352258'
py310 run-test: commands[0] | python -m unittest tests/test_etree_import.py -k before
E
======================================================================
ERROR: test_import_etree_before (tests.test_etree_import.TestElementTreeImport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/xmlschema/tests/test_etree_import.py", line 80, in test_import_etree_before
    xmlschema_etree = importlib.import_module('xmlschema.etree')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/xmlschema/xmlschema/__init__.py", line 20, in <module>
    from .dataobjects import DataElement, DataElementConverter, DataBindingConverter
  File "/tmp/xmlschema/xmlschema/dataobjects.py", line 20, in <module>
    from . import validators
  File "/tmp/xmlschema/xmlschema/validators/__init__.py", line 38, in <module>
    from .schema import XMLSchemaMeta, XMLSchemaBase, XMLSchema, XMLSchema10, XMLSchema11
  File "/tmp/xmlschema/xmlschema/validators/schema.py", line 1900, in <module>
    class XMLSchema10(XMLSchemaBase):
  File "/tmp/xmlschema/xmlschema/validators/schema.py", line 130, in __new__
    meta_schema = meta_schema_class.create_meta_schema(schema_location)
  File "/tmp/xmlschema/xmlschema/validators/schema.py", line 718, in create_meta_schema
    meta_schema = meta_schema_class(source, XSD_NAMESPACE, global_maps=global_maps,
  File "/tmp/xmlschema/xmlschema/validators/schema.py", line 324, in __init__
    self.source = XMLResource(source, base_url, allow, defuse, timeout)
  File "/tmp/xmlschema/xmlschema/resources.py", line 421, in __init__
    self.parse(source, lazy)
  File "/tmp/xmlschema/xmlschema/resources.py", line 622, in parse
    url = normalize_url(source)
  File "/tmp/xmlschema/xmlschema/resources.py", line 171, in normalize_url
    return path.normalize().as_uri()
  File "/tmp/xmlschema/xmlschema/resources.py", line 142, in normalize
    return self._from_parts((normalized_path,), init=False)
TypeError: PurePath._from_parts() got an unexpected keyword argument 'init'

----------------------------------------------------------------------
Ran 1 test in 0.237s

FAILED (errors=1)
ERROR: InvocationError for command /home/mgorny/.tox/xmlschema/py310/bin/python -m unittest tests/test_etree_import.py -k before (exited with code 1)
____________________________________________________________________ summary _____________________________________________________________________
ERROR:   py310: commands failed
```

**Comment by brunato** [comment]
Maybe *protected* API, but currently is the only way that i found for overwhelming the limits of `PurePath` classes. For managing location hints i can't use concrete Path classes.

Anyway in this case i can remove the _init_ argument, because is not really used by PurePath. 

Thanks

**Comment by mgorny** [comment]
Thanks! It works for me now.
