### ISSUE TITLE
How to access annotations of an enumeration

### ISSUE THREAD

**Issue by juliusdanek** [sissaschool/xmlschema#255]
One of the schemas I am working with ([MISMO](https://www.mismo.org/standards-and-resources/residential-specifications/xml-schema)) contains the following simpleType. How can I access the annotations of the enumerations?

Getting the enumeration is simple, however it returns the enumerations as simple strings, without the documentation. Any chance I can also access the annotation + documentation?

```python
type = schema.types['AcceptableSigningMethodBase']
type.enumeration
```

```xml
<xsd:simpleType name="AcceptableSigningMethodBase">
	<xsd:annotation>
		<xsd:documentation>Term: Acceptable Signing Method Type Definition: An instruction as to the signing methods that are acceptable for this document. It does not reflect a document instance state.</xsd:documentation>
	</xsd:annotation>
	<xsd:restriction base="MISMOEnum_Base">
		<xsd:enumeration value="Any">
			<xsd:annotation>
				<xsd:documentation>The document requires either electronic or wet signatures.</xsd:documentation>
			</xsd:annotation>
		</xsd:enumeration>
		<xsd:enumeration value="Electronic">
			<xsd:annotation>
				<xsd:documentation>The document requires electronic signatures.</xsd:documentation>
			</xsd:annotation>
		</xsd:enumeration>
		<xsd:enumeration value="None">
			<xsd:annotation>
				<xsd:documentation>The document does not require signatures.</xsd:documentation>
			</xsd:annotation>
		</xsd:enumeration>
		<xsd:enumeration value="Wet">
			<xsd:annotation>
				<xsd:documentation>The document requires an original handwritten signature.</xsd:documentation>
			</xsd:annotation>
		</xsd:enumeration>
	</xsd:restriction>
</xsd:simpleType>
```

**Comment by brunato** [comment]
Hi,
currently annotations of enumeration facets are not parsed.

The` type.enumeration` is a property that extracts the list of values from the facets object. 
For accessing the facet object:

```pycon
>>> xsd_type = schema.types['AcceptableSigningMethodBase']
>>> enumeration = xsd_type.get_facet('{http://www.w3.org/2001/XMLSchema}enumeration')
>>> enumeration
XsdEnumerationFacets(['Any', 'Electronic', 'None', 'Wet'])
>>> enumeration.enumeration
['Any', 'Electronic', 'None', 'Wet']
```

A property/method (maybe lazy) for parsing and accessing annotations could be developed. Meanwhile a manner for accessing unparsed annotations is: 

```pycon
>>> enumeration[0]
<Element '{http://www.w3.org/2001/XMLSchema}enumeration' at 0x7fa7489cb450>
>>> enumeration[0].get('value')
'Any'
>>> enumeration[0]
<Element '{http://www.w3.org/2001/XMLSchema}enumeration' at 0x7fa7489cb450>
>>> enumeration[0][:]
[<Element '{http://www.w3.org/2001/XMLSchema}annotation' at 0x7fa7489cb4a0>]
```

**Comment by juliusdanek** [comment]
Thank you Brunato! Very much appreciate your answer. Let me try this out and get back to you.

**Comment by brunato** [comment]
Hi,
with release v1.7.0 a method is added for retrieving annotations of enumeration facets:

```pycon
>>> import xmlschema
>>> schema = xmlschema.XMLSchema11("MISMOEnumeratedTypesB344.xsd")
>>> xsd_type = schema.types['AcceptableSigningMethodBase']
>>> enumeration = xsd_type.get_facet('{http://www.w3.org/2001/XMLSchema}enumeration')
>>> enumeration.get_annotation(0)
XsdAnnotation('The document requires either electronic ')
>>> str(enumeration.get_annotation(0))
'The document requires either electronic or wet signatures.'
>>> str(enumeration.get_annotation(1))
'The document requires electronic signatures.'
>>> str(enumeration.get_annotation(2))
'The document does not require signatures.'
>>> str(enumeration.get_annotation(3))
'The document requires an original handwritten signature.'
```

It's defined also for pattern facets. It takes the index of the enumeration item, if you exceed an error is raised:

```pycon
>>> str(enumeration.get_annotation(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brunato/Development/projects/xmlschema/xmlschema/validators/facets.py", line 573, in get_annotation
    for child in self._elements[i]:
IndexError: list index out of range
```

Note: In the new release all annotations are built lazily (but annotations are still validated against the meta-schema).

**Comment by TheMule71** [comment]
I hope you don't mind me commenting on a closed issue. The following code seem to work in 1.6.4:
```
import platform
import xmlschema

_xml_schema_1_2_1 = "Schema_del_file_xml_FatturaPA_versione_1.2.1.xsd"
_old_xsd_specs = "xmldsig-core-schema.xsd"

validator = xmlschema.XMLSchema(
    _xml_schema_1_2_1,
    locations={"http://www.w3.org/2000/09/xmldsig#": _old_xsd_specs},
)

TipoDocumentoType = validator.types['TipoDocumentoType']
enum = TipoDocumentoType.get_facet('{http://www.w3.org/2001/XMLSchema}enumeration')

print("python/xmlschema {}/{}".format(platform.python_version(), xmlschema.__version__))
for e in enum:
    print(e.get('value'), e[:][0][:][0].text)
```

```
python/xmlschema 3.6.15/1.6.4
TD01 Fattura
TD02 Acconto / anticipo su fattura
TD03 Acconto / anticipo su parcella
TD04 Nota di credito
TD05 Nota di debito
TD06 Parcella
TD16 Integrazione fattura reverse charge interno
TD17 Integrazione/autofattura per acquisto servizi dall'estero
TD18 Integrazione per acquisto di beni intracomunitari
TD19 Integrazione/autofattura per acquisto di beni ex art.17 c.2 DPR 633/72
TD20 Autofattura per regolarizzazione e integrazione delle fatture (ex art.6 c.8 e 9-bis d.lgs.471/97 o art.46 c.5 D.L. 331/93
TD21 Autofattura per splafonamento
TD22 Estrazione benida Deposito IVA
TD23 Estrazione beni da Deposito IVA con versamento dell'IVA
TD24 Fattura differita di cui all'art.21, comma 4, terzo periodo lett. a) DPR 633/72
TD25 Fattura differita di cui all'art.21, comma 4, terzo periodo lett. b) DPR 633/72
TD26 Cessione di beni ammortizzabili e per passaggi interni (ex art.36 DPR 633/72)
TD27 Fattura per autoconsumo o per cessioni gratuite senza rivalsa
```

The relevant part in the Schema:
```
  <xs:simpleType name="TipoDocumentoType">
    <xs:restriction base="xs:string">
      <xs:length value="4" />
      <xs:enumeration value="TD01">
        <xs:annotation>
          <xs:documentation>Fattura</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      ...
```
