### ISSUE TITLE
UNC path support (Windows)

### ISSUE THREAD

**Issue by Lois31** [sissaschool/xmlschema#268]
Hello,

For the deployment and use of our software, we use shared network hard drives (filer) and under Windows we use the UNC path to address them.
However, an error appears when using xmlschema validation with this type of path.

Below is a simple example of use:

```
# coding: utf8

###############################################################################
# import
import os
import sys
import argparse
import xmlschema

###############################################################################
# Main
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('xml_file', help='The UNC path of the xml file')
    parser.add_argument('xsd_file', help='The UNC path of the xsd file')
    args = parser.parse_args()

    if not os.path.exists(args.xml_file):
        print('Error: cannot access %s: No such file' % str(args.xml_file))
        sys.exit(1)
    if not os.path.exists(args.xsd_file):
        print('Error: cannot access %s: No such file' % str(args.xsd_file))
        sys.exit(1)

    # exec_dir   = os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(__file__)
    xsd_schema = xmlschema.XMLSchema(args.xsd_file)

    print('Info: Validation of the XML file: %s' % args.xml_file)
    try:
        xsd_schema.validate(args.xml_file)
    except xmlschema.validators.exceptions.XMLSchemaValidationError as err:
        print('Error: %s' % str(err))
```

```
python \\filer01\MY_HOME\dev\XMLSCHEMA\xml_valid.py \\filer02\PROJECT_HOME\test.xml \\filer01\MY_HOME\dev\XMLSCHEMA\test.xsd
Traceback (most recent call last):
  File "I:\PYTHON\V3.7.9\Windows\lib\urllib\request.py", line 1506, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] The specified path was not found: '\\MY_HOME\dev\XMLSCHEMA\test.xsd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\filer01\MY_HOME\dev\XMLSCHEMA\xml_valid.py", line 27, in <module>
    xsd_schema = xmlschema.XMLSchema(args.xsd_file)
  File "H:\dev\XMLSCHEMA\python_env\windows\lib\site-packages\xmlschema\validators\schema.py", line 350, in __init__
    self.source = XMLResource(source, base_url, allow, defuse, timeout)
  File "H:\dev\XMLSCHEMA\python_env\windows\lib\site-packages\xmlschema\resources.py", line 462, in __init__
    self.parse(source, lazy)
  File "H:\dev\XMLSCHEMA\python_env\windows\lib\site-packages\xmlschema\resources.py", line 684, in parse
    with urlopen(url, timeout=self._timeout) as resource:
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 1484, in file_open
    return self.open_local_file(req)
  File "H:\PYTHON\V3.7.9-1\BINARIES\Windows\lib\urllib\request.py", line 1523, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] The specified path was not found: '\\MY_HOME\dev\XMLSCHEMA\test.xsd'>
```

Everything works correctly when replacing the UNC path by path with drive:
with:
- H:\ mount on \\filer01\MY_HOME
- P:\ mount on \\filer02\PROJECT_HOME

```
python H:\dev\XMLSCHEMA\xml_valid.py P:\test.xml  H:\dev\XMLSCHEMA\test.xsd
Info: Validation of the XML file: P:\test.xml
```

**Comment by brunato** [comment]
Hi,

for filepath normalization i use pathlib.PurePath classes (PureWindowsPath under Windows OS). I'll check where is the problem explicitly applying your case's paths to PureWindowsPath.

Looking at traceback i deduce that `args.xsd_file` that generates the error is `\\filer01\MY_HOME\dev\XMLSCHEMA\test.xsd`.

**Comment by brunato** [comment]
I didn't found an issue with UNC paths. They are processed by `pathlib.PureWindowsPath` and produce a valid URI path.
See the test that I've added.

If you provide other details or failed UNC path i will check them.

Best regards

**Comment by Lois31** [comment]
The problematic part of the code is in the file `resources.py` line 669:
```
        if isinstance(source, (str, bytes)):
            if is_url(source):
                # source is a string containing an URL or a file path
                if isinstance(source, str):
                    url = normalize_url(source)
                else:
                    url = normalize_url(source.decode())
                self._access_control(url)

                _url, self._url = self._url, url
                try:
                    with urlopen(url, timeout=self._timeout) as resource:
```

The following UNC path `\\filer01\MY_HOME\dev\XMLSCHEMA\test.xsd` is detected as a url and normalized via the `normalize_url` function as follows: `file://filer01/MY_HOME/dev/XMLSCHEMA/test.xsd`

When you try to open the "url" `file://filer01/MY_HOME/dev/XMLSCHEMA/test.xsd` via the `urlopen` function the following exception is raised:
```
Traceback (most recent call last):
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 1506, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: '\\MY_HOME\\dev\\XMLSCHEMA\\test.xsd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pure_path.py", line 160, in <module>
    with urlopen(xsd_schema) as resource:
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 1484, in file_open
    return self.open_local_file(req)
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 1523, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] The specified path was not found: '\\MY_HOME\\dev\\XMLSCHEMA\\test.xsd'>
```

In the `resources.py` file line 671, there is a comment specifying: `# source is a string containing an URL or a file path`.
However, the case of a file specified via a UNC path (\\filer01\MY_HOME\dev\XMLSCHEMA\test.xsd)  does not seem to be taken into account correctly.

In order to reprtoduce the behavior, I have simplified you code as follow:

**pure_path.py**
```
# coding: utf8

###############################################################################
# import
import os
import sys
import argparse
import pathlib

from typing import cast, Any
from urllib.request import urlopen
from urllib.parse import urlsplit, urlunsplit, unquote, quote_from_bytes


###############################################################################
# Main
###
# URL normalization (that fixes many headaches :)
class _PurePath(pathlib.PurePath):
    """
    A version of pathlib.PurePath adapted for managing the creation
    from URIs and the simple normalization of paths.
    """
    _from_parts: Any
    _flavour: Any

    def __new__(cls, *args):
        if cls is _PurePath:
            cls = _WindowsPurePath if os.name == 'nt' else _PosixPurePath
        return cast('_PurePath', cls._from_parts(args))

    @classmethod
    def from_uri(cls, uri):
        uri = uri.strip()
        if not uri:
            # raise XMLSchemaValueError("Empty URI provided!")
            print('EXCEPTION Empty URI provided!')
            sys.exit(-1)

        if uri.startswith(r'\\'):
            return _WindowsPurePath(uri)  # UNC path
        elif uri.startswith('/'):
            return cls(uri)

        parts = urlsplit(uri)
        if not parts.scheme:
            return cls(uri)
        elif parts.scheme in DRIVE_LETTERS and len(parts.scheme) == 1:
            return _WindowsPurePath(uri)  # Eg. k:/Python/lib/....
        elif parts.scheme != 'file':
            return _PosixPurePath(unquote(parts.path))

        # Get file URI path because urlsplit does not parse it well
        start = 7 if uri.startswith('file:///') else 5
        if parts.query:
            path = uri[start:uri.index('?')]
        elif parts.fragment:
            path = uri[start:uri.index('#')]
        else:
            path = uri[start:]

        if ':' in path:
            # Windows path with a drive
            pos = path.index(':')
            if pos == 2 and path[0] == '/' and path[1] in DRIVE_LETTERS:
                return _WindowsPurePath(unquote(path[1:]))

            obj = _WindowsPurePath(unquote(path))
            if len(obj.drive) != 2 or obj.drive[1] != ':':
                # raise XMLSchemaValueError("Invalid URI {!r}".format(uri))
                print('EXCEPTION Invalid URI {!r}'.format(uri))
                sys.exit(-1)
            return obj

        if '\\' in path:
            return _WindowsPurePath(unquote(path))
        return cls(unquote(path))

    def as_uri(self):
        if not self.is_absolute():
            uri: str = self._flavour.make_uri(self)
            while uri.startswith('file:/'):
                uri = uri.replace('file:/', 'file:', 1)
            return uri
        return cast(str, self._flavour.make_uri(self))

    def normalize(self):
        normalized_path = self._flavour.pathmod.normpath(str(self))
        return cast('_PurePath', self._from_parts((normalized_path,)))


class _PosixPurePath(_PurePath, pathlib.PurePosixPath):
    __slots__ = ()


class _WindowsPurePath(_PurePath, pathlib.PureWindowsPath):
    __slots__ = ()


def is_local_scheme(scheme):
    return not scheme or scheme == 'file' or scheme in DRIVE_LETTERS

def normalize_url(url, base_url = None, keep_relative = False):
    """
    Returns a normalized URL eventually joining it to a base URL if it's a relative path.
    Path names are converted to 'file' scheme URLs.
    :param url: a relative or absolute URL.
    :param base_url: a reference base URL.
    :param keep_relative: if set to `True` keeps relative file paths, which would \
    not strictly conformant to specification (RFC 8089), because *urlopen()* doesn't \
    accept a simple pathname.
    :return: a normalized URL string.
    """
    url_parts = urlsplit(url)
    if not is_local_scheme(url_parts.scheme):
        print('IS NOT LOCAL SCHEME')
        return url_parts.geturl()

    path = _PurePath.from_uri(url)
    if path.is_absolute():
        print('PATH IS ABSOLUTE')
        return path.normalize().as_uri()

    if base_url is not None:
        print('BASE URL IS NOT NONE')
        base_url_parts = urlsplit(base_url)
        base_path = _PurePath.from_uri(base_url)
        if is_local_scheme(base_url_parts.scheme):
            path = base_path.joinpath(path)
        elif not url_parts.scheme:
            path = base_path.joinpath(path).normalize()
            return urlunsplit((
                base_url_parts.scheme,
                base_url_parts.netloc,
                quote_from_bytes(bytes(path)),
                url_parts.query,
                url_parts.fragment
            ))

    if path.is_absolute() or keep_relative:
        return path.normalize().as_uri()

    base_path = _PurePath(os.getcwd())
    return base_path.joinpath(path).normalize().as_uri()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('xsd_file', help='The UNC path of the xsd file')
    args = parser.parse_args()

    if not os.path.exists(args.xsd_file):
        print('Error: cannot access %s: No such file' % str(args.xsd_file))
        sys.exit(1)

    print(args.xsd_file)
    xsd_schema = normalize_url(args.xsd_file)
    print(xsd_schema)
    with urlopen(xsd_schema) as resource:
        print(ressource)

``` 

To use it just type the following command:
`python pure_path.py \\filer01\MY_HOME\dev\XMLSCHEMA\test.xsd`

**Comment by brunato** [comment]
Hi,
I've checked this, the URL is right but seems to be urlopen that cannot process a file URL that contains an UNC path.

**Comment by brunato** [comment]
I'will check urllib with file URIs and try to find a solution for this or alternatively use open() for opening file paths. This could be for the next minor release.

**Comment by brunato** [comment]
Could you check if _urlopen_ can access a file in your UNC share using following _file_ URI formats?

  * `urlopen('file://filer01/MY_HOME/dev/XMLSCHEMA/test.xsd')`
  * `urlopen('file:////filer01/MY_HOME/dev/XMLSCHEMA/test.xsd')`

Thank you

**Comment by Lois31** [comment]
```
urlopen('file://filer01/MY_HOME/dev/XMLSCHEMA/test.xsd')
Traceback (most recent call last):
  File "H:\PYTHON\V3.7.9\BINARIES\Windows\lib\urllib\request.py", line 1506, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] 
The specified path was not found: '\\MY_HOME\\dev\\XMLSCHEMA\\test.xsd'
```

```
urlopen('file:////filer01/MY_HOME/dev/XMLSCHEMA/test.xsd')
<addinfourl at 2314226310280 whose fp = <_io.BufferedReader name='\\\\filer01\\MY_HOME\\dev\\XMLSCHEMA\\test.xsd'>>
```

The second solution works with the four _'/'_

**Comment by brunato** [comment]
Hi, 
try if the new release v1.8.2 works with UNC paths.

Thank you

**Comment by Lois31** [comment]
Hello,
It works fine.
Thank you for the correction!
