### ISSUE TITLE
Failure at parsing Ecore.xsd

### ISSUE THREAD

**Issue by ddoyaguez** [sissaschool/xmlschema#287]
Hi. I am trying to validate ecore metamodel files by making xmlschema read the following ecore XSD file
https://github.com/cloudsmith/org.eclipse.emf/blob/master/plugins/org.eclipse.emf.ecore/model/Ecore.xsd

Im using Python 3.10.

The problem is that when I try to open the previously downloaded XSD doing
`
ecore_schema = XMLSchema('Ecore.xsd')
`

It fails with the following error:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/schemas.py", line 510, in __init__
    self.maps.build()
  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/global_maps.py", line 643, in build
    self.lookup_type(qname)
  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/global_maps.py", line 255, in lookup_type
    return cast(BaseXsdType, self._build_global(obj, qname, self.types))
  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/global_maps.py", line 314, in _build_global
    global_map[qname] = factory_or_class(elem, schema)

  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/schemas.py", line 790, in simple_type_factory
    annotation = XsdAnnotation(child, schema, parent)
  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/xsdbase.py", line 297, in __init__
    self.elem = elem
  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/xsdbase.py", line 309, in __setattr__
    self._parse()
  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/xsdbase.py", line 680, in _parse
    self.parse_error("wrong attribute %r for appinfo declaration." % key)
  File "VENV/lib64/python3.10/site-packages/xmlschema/validators/xsdbase.py", line 188, in parse_error
    raise error
xmlschema.validators.exceptions.XMLSchemaParseError: wrong attribute '{http://www.eclipse.org/emf/2002/Ecore}key' for appinfo declaration:

Schema:

  <xsd:annotation xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:appinfo ecore:key="typeParameters" source="http://www.eclipse.org/emf/2002/Ecore">
      <typeParameter name="E" />
    </xsd:appinfo>
  </xsd:annotation>

Path: /xsd:schema/xsd:simpleType[14]/xsd:annotation

Schema URL: file:///PATH/Ecore.xsd
```

I have looked into xsdbase.py, class XsdAnnotation and _parse function is too strict on line 679
```
if key != 'source':
    self.parse_error("wrong attribute %r for appinfo declaration." % key)
```
It is not taking into account the {any attributes with non-schema namespace} (as stated in docstring, that got it well)
```
<appinfo
          source = anyURI
          {any attributes with non-schema namespace . . .}>
          Content: ({any})*
</appinfo>
```

**Comment by brunato** [comment]
Hi,

it could be old code, I removed also for xs:documentation.
Eventual errors with other attributes in XSD namespace can be better detected by validation against the meta-schema.

The fix is available with release v1.10.0.

Thank you
