### ISSUE TITLE
Validating sub schema

### ISSUE THREAD

**Issue by PabloAJomer** [sissaschool/xmlschema#326]
Hi I am in need of some help. I have looked trough the code examples and tests pretty throughly but I'm having trouble finding support for my use case. I would like to validate only a sub part of my xml against my XSD schema but I get an error while trying to do this.

Is there support for this in the library and if so are there any examples of how this can be done?

We currently solved it by reorganizing the XSD but that feels a bit hacky.

Below are the example files we have.
_test.py_
```python
from xml.etree import ElementTree

from xmlschema import XMLSchema


def main() -> None:
    schema = XMLSchema("./camt.054.001.02.xsd")
    document = ElementTree.parse("./document.xml")
    entries = document.findall("*/Ntfctn/Ntry", namespaces={"": "urn:iso:std:iso:20022:tech:xsd:camt.054.001.02"})
    for entry in entries:
        schema.validate(
            entry,
            # schema_path="./xs:complexType/xs:sequence/xs:element[@name='Ntry']",
            namespaces={"": "urn:iso:std:iso:20022:tech:xsd:camt.054.001.02", "xs": "http://www.w3.org/2001/XMLSchema"},
        )


main()
```
_error.out_
```error
_redacted_/bin/python _redacted_/test.py 
Traceback (most recent call last):
  File "_redacted_/test.py", line 18, in <module>
    main()
  File "_redacted_/test.py", line 11, in main
    schema.validate(
  File "_redacted_/lib/python3.10/site-packages/xmlschema/validators/schemas.py", line 1716, in validate
    raise error
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating <Element '{urn:iso:std:iso:20022:tech:xsd:camt.054.001.02}Ntry' at 0x110a598a0> with XMLSchema10(name='camt.054.001.02.xsd', namespace='urn:iso:std:iso:20022:tech:xsd:camt.054.001.02'):

Reason: <Element '{urn:iso:std:iso:20022:tech:xsd:camt.054.001.02}Ntry' at 0x110a598a0> is not an element of the schema

Instance:

  <Ntry xmlns="urn:iso:std:iso:20022:tech:xsd:camt.054.001.02">
      <NtryRef>TEST-1234-1</NtryRef>
      <Amt Ccy="USD">1.00</Amt>
      <CdtDbtInd>CRDT</CdtDbtInd>
      <Sts>BOOK</Sts>
      <BookgDt>
          <Dt>2021-09-09</Dt>
      </BookgDt>
      <ValDt>
          <Dt>2021-09-09</Dt>
      </ValDt>
      <AcctSvcrRef>1234</AcctSvcrRef>
      <BkTxCd>
          <Domn>
              <Cd>PMNT</Cd>
              <Fmly>
                  <Cd>CD</Cd>
                  <SubFmlyCd>DC</SubFmlyCd>
              </Fmly>
          </Domn>
      ...
      ...
  </Ntry>

Path: /Ntry
```

_camt.054.001.02.xsd_
[camt.054.001.02.xsd.log](https://github.com/sissaschool/xmlschema/files/9652290/camt.054.001.02.xsd.log)

_document.xml_
[document.xml.log](https://github.com/sissaschool/xmlschema/files/9652285/document.xml.log)

**Comment by brunato** [comment]
Hi,

it's better to let xmlschema to fetch namespaces, e.g.:

```pycon
>>> from xmlschema import XMLSchema
>>> schema = XMLSchema('camt.054.001.02.xsd')
>>> schema.validate('document.xml')
```

About paths: usually _schema_path_ is not needed, because path traversal does not consider types, but only elements or attributes (that can be defined in different schema sources). If the XML that has to be validated is only a chunk of the whole document covered by the schema provide a _schema_path_ (yuo can test path finding on schema using `schema.findall/find()` APIs).

So for your case can be:

```pycon
>>> schema.validate('document.xml', path='*/Ntfctn/Ntry')
```

with a wrong path no exception/warning currently appears (maybe will be in a future release), but this can be checked testing the path or using the decoding API:

```pycon
>>> schema.decode('document.xml', path='*/Ntfctn/Ntry')
{'NtryRef': 'TEST-1234-1', 'Amt': {'@Ccy': 'USD', '$': Decimal('1.00')}, 'CdtDbtInd': 'CRDT', 'Sts': 'BOOK', 'BookgDt': {'Dt': '2021-09-09'}, 'ValDt': {'Dt': '2021-09-09'}, 'AcctSvcrRef': '1234', 'BkTxCd': {'Domn': {'Cd': 'PMNT', 'Fmly': {'Cd': 'CD', 'SubFmlyCd': 'DC'}}, 'Prtry': {'Cd': '1234', 'Issr': 'TEST'}}, 'NtryDtls': [{'TxDtls': [{'Refs': {'AcctSvcrRef': '*1234', 'InstrId': 'TEST-1234'}, 'AmtDtls': {'TxAmt': {'Amt': {'@Ccy': 'USD', '$': Decimal('1.00')}}}, 'RltdPties': {'Dbtr': {'Nm': 'Testsystem', 'PstlAdr': {'PstCd': '1234', 'TwnNm': 'New York', 'AdrLine': ['NZ1234']}}, 'DbtrAcct': {'Id': {'Othr': {'Id': '1234', 'SchmeNm': {'Cd': 'BBAN'}}}}, 'Cdtr': {'Nm': 'TEST', 'PstlAdr': {'PstCd': '1234', 'TwnNm': 'New York', 'Ctry': 'NO', 'AdrLine': ['NZ1234']}}, 'CdtrAcct': {'Id': {'Othr': {'Id': 'Id-1234', 'SchmeNm': {'Cd': 'BBAN'}}}}}, 'Purp': {'Prtry': 'Testsystem'}, 'RmtInf': {'Strd': [{'RfrdDocInf': [{'Tp': {'CdOrPrtry': {'Cd': 'CINV'}}, 'Nb': 'TEST-123456787'}], 'RfrdDocAmt': {'RmtdAmt': {'@Ccy': 'USD', '$': Decimal('1.00')}}}]}, 'RltdDts': {'IntrBkSttlmDt': '2021-09-09'}}]}]}
```

**Comment by brunato** [comment]
Found a bug in `XMLSchema.iter_decode()` (called by `validate()`) if a *schema_path* is provided without a *path*. It will be fixed in the next bugfix release.

After that your script should works providing a proper `schema_path` to the matching XSD element(e.g. `/Document/*/Ntfctn/Ntry` or `.//Ntry`). Path selection on built schemas considers only XPath element and attributes nodes in order to found a match with the XML path.

**Comment by brunato** [comment]
Bugfix release v2.1.1 is available. For your case the script can be changed as follows:

```python
from xml.etree import ElementTree

from xmlschema import XMLSchema


def main() -> None:
    schema = XMLSchema("./camt.054.001.02.xsd")
    document = ElementTree.parse("./document.xml")
    entries = document.findall("*/Ntfctn/Ntry", namespaces={"": "urn:iso:std:iso:20022:tech:xsd:camt.054.001.02"})

    for entry in entries:
        schema.validate(
            entry,
            schema_path="/Document/*/Ntfctn/Ntry",
            namespaces={"": "urn:iso:std:iso:20022:tech:xsd:camt.054.001.02"},
        )


main()
```

Note that schema_path includes the root element, this because the XPath selection on build schemas has to consider the document level.
