### ISSUE TITLE
XSD schema parsing error that seems undetected by xmllint

### ISSUE THREAD

**Issue by bernt-matthias** [sissaschool/xmlschema#336]
We use a [xsd file](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/xsd/galaxy.xsd) in a project that is currently lintes with `xmllint  --noout lib/galaxy/tool_util/xsd/galaxy.xsd`. 

I was now playing around with `xmlschema` (looking for a way to access schema annotation during xml parsing), but unfortunately `xmlschema` does not like this schema:

Apparently the error is due to https://github.com/galaxyproject/galaxy/blob/076a695afd90d9ad7b140aabd02871422496c770/lib/galaxy/tool_util/xsd/galaxy.xsd#L5296 

Wondering if this is a problem with xmllint (and our xsd) or an issue in `xmlschema`?

```
Traceback (most recent call last):
  File "/tmp/schematest/./test.py", line 6, in <module>
    for x in iter_decode("mcl.xml", schema="galaxy.xsd", validation='skip'):
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/documents.py", line 271, in iter_decode
    source, _schema = get_context(xml_document, schema, cls, locations, base_url,
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/documents.py", line 89, in get_context
    return resource, cls(schema, locations=locations, base_url=base_url,
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/validators/schemas.py", line 503, in __init__
    self.maps.build()
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/validators/global_maps.py", line 659, in build
    self.check(filter(lambda x: x.meta_schema is not None, not_built_schemas), self.validation)
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/validators/global_maps.py", line 725, in check
    xsd_type.content.check_model()
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/validators/groups.py", line 811, in check_model
    raise XMLSchemaModelError(self, msg)
xmlschema.validators.exceptions.XMLSchemaModelError: Element Declarations Consistent violation between XsdElement(name='discover_datasets', occurs=[1, 1]) and XsdElement(name='discover_datasets', occurs=[1, 1]): match the same name but with different types:

Schema:

  <xs:sequence xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:group ref="OutputDataElement" minOccurs="0" maxOccurs="unbounded" />
    <xs:group ref="OutputCollectionElement" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>

Path: /xs:schema/xs:complexType[87]/xs:sequence

Schema URL: file:///tmp/schematest/galaxy.xsd
```

```
Traceback (most recent call last):
  File "/tmp/schematest/./test.py", line 5, in <module>
    for x in iter_decode("mcl.xml", schema="galaxy.xsd", validation='strict'):
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/documents.py", line 271, in iter_decode
    source, _schema = get_context(xml_document, schema, cls, locations, base_url,
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/documents.py", line 89, in get_context
    return resource, cls(schema, locations=locations, base_url=base_url,
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/validators/schemas.py", line 503, in __init__
    self.maps.build()
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/validators/global_maps.py", line 659, in build
    self.check(filter(lambda x: x.meta_schema is not None, not_built_schemas), self.validation)
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/validators/global_maps.py", line 725, in check
    xsd_type.content.check_model()
  File "/tmp/.venv-xmlschema/lib/python3.10/site-packages/xmlschema/validators/groups.py", line 836, in check_model
    raise XMLSchemaModelError(self, msg.format(pe, e))
xmlschema.validators.exceptions.XMLSchemaModelError: Unique Particle Attribution violation between XsdElement(name='discover_datasets', occurs=[1, 1]) and XsdElement(name='discover_datasets', occurs=[1, 1]):

Schema:

  <xs:sequence xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:group ref="OutputDataElement" minOccurs="0" maxOccurs="unbounded" />
    <xs:group ref="OutputCollectionElement" minOccurs="0" maxOccurs="unbounded" />
  </xs:sequence>

Path: /xs:schema/xs:complexType[87]/xs:sequence

Schema URL: file:///tmp/schematest/galaxy.xsd
```

**Comment by brunato** [comment]
This is a problem with _xmllint_ that does not detect the UPA violation in your XSD.

Tried also _xerces_ validator, these are the errors reported:

```
[Error] galaxy.xsd:5296:33:cos-element-consistent: Error for type 'Output'. Multiple elements with name 'discover_datasets', with different types, appear in the model group.
[Error] galaxy.xsd:5296:33:cos-nonambig: filter and filter (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.
```

**Comment by bernt-matthias** [comment]
Thought so. Thanks a lot for checking.
