### ISSUE TITLE
Getting error from xmlschema-validate.exe trying to validate XSLT 3.0 stylesheet against XSD 1.1 schema for XSLT 3: AttributeError: 'AttributeNode' object has no attribute 'is_schema_element'

### ISSUE THREAD

**Issue by martin-honnen** [sissaschool/xmlschema#344]
I am exploring the use of `xmlschema-validate.exe` as a command line tool to validate XML instances against schemas; in one attempt I have tried to validate a simple XSLT stylesheet (` & 'C:\Users\marti\AppData\Roaming\Python\Python39\Scripts\xmlschema-validate.exe' --version 1.1 --schema .\schema-for-xslt30.xsd .\xslt3-sheet1-invalid.xsl`) and get an error `AttributeError: 'AttributeNode' object has no attribute 'is_schema_element'`; details are below:

```
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="3.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  exclude-result-prefixes="#all"
  expand-text="yes">

  <xsl:mode on-no-match="shallow-coy"/>

  <xsl:template match="/" name="xsl:inital-template">
    <xsl:next-match/>
    <xsl:comment>Run with {system-property('xsl:product-name')} {system-property('xsl:product-version')} {system-property('Q{http://saxon.sf.net/}platform')}</xsl:comment>
  </xsl:template>
  
</xsl:stylesheet>
```
XSD 1.1 schema for XSLT 3 is attached, too long to paste inline and direct attachment of the unzipped file didn't work either due to non supported file type.
[schema-for-xslt30.zip](https://github.com/sissaschool/xmlschema/files/11294907/schema-for-xslt30.zip)

I get some longish stack trace show below; is that due to a lack of me providing the right arguments to the CLI tool or due to a bug in the tool?

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\marti\AppData\Roaming\Python\Python39\Scripts\xmlschema-validate.exe\__main__.py", line 7, in <module>
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\xmlschema\cli.py", line 260, in validate
    errors = list(iter_errors(filepath, schema=args.schema, cls=schema_class,
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\xmlschema\documents.py", line 220, in iter_errors
    source, schema = get_context(xml_document, schema, cls, locations, base_url,
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\xmlschema\documents.py", line 89, in get_context
    return resource, cls(schema, locations=locations, base_url=base_url,
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\xmlschema\validators\schemas.py", line 503, in __init__
    self.maps.build()
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\xmlschema\validators\global_maps.py", line 667, in build
    obj.build()
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\xmlschema\validators\assertions.py", line 106, in build
    self.token = self.parser.parse(self.path)
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath2\xpath2_parser.py", line 523, in parse
    for _ in root_token.select(context):
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath_tokens.py", line 107, in select
    item = self.evaluate(context)
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath2\_xpath2_operators.py", line 193, in evaluate_quantified_expressions
    for results in copy(context).iter_product(selectors, varnames):
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath_context.py", line 285, in iter_product
    value = next(iterators[k])
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath1\_xpath1_operators.py", line 737, in select_child_path
    for result in self[1].select(context):
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath1\_xpath1_operators.py", line 820, in select_predicate
    for _ in context.inner_focus_select(self[0]):
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath_context.py", line 254, in inner_focus_select
    results = [x for x in token.select(copy(self))]
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath_context.py", line 254, in <listcomp>
    results = [x for x in token.select(copy(self))]
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath_tokens.py", line 107, in select
    item = self.evaluate(context)
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath1\_xpath1_functions.py", line 236, in evaluate_normalize_space_function
    arg = self.get_argument(context, default_to_context=True, default='', cls=str)
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath_tokens.py", line 297, in get_argument
    for k, result in enumerate(token.select(copy(context))):
  File "C:\Users\marti\AppData\Roaming\Python\Python39\site-packages\elementpath\xpath1\_xpath1_operators.py", line 409, in select_self_shortcut
    if item.is_schema_element():
AttributeError: 'AttributeNode' object has no attribute 'is_schema_element'
```

**Comment by brunato** [comment]
Hi,
the reported error is fixed by the latest release of _elementpath_, but a restriction checking error then happens later.  This needs a partial rewriting of XSD 1.1 restriction checking, until the next minor release the script will be not usable with XSLT 3.0 schema.

A workaround for this is building the schema using `validation='lax'`:

```python
import xmlschema

schema = xmlschema.XMLSchema11('schema-for-xslt30.xsd', validation='lax')
```

**Comment by martin-honnen** [comment]
Thanks, @brunato , I will use the workaround until a release has the fix for the restriction checking error.

**Comment by brunato** [comment]
Hi, 
with v2.3.0 of _xmlschema_ the parsing of XSLT 3.0 should work also in strict validation mode.
