### ISSUE TITLE
2.3.0: three tests fails with Python 3.7.16

### ISSUE THREAD

**Issue by mtelka** [sissaschool/xmlschema#348]
I tested version 2.3.0 with Python 3.7.16 and I found that following three tests fails:
```
======================================================================
FAIL: test_extra_validator__issue_291 (tests.test_typing.TestTyping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$(BUILD_DIR)/tests/test_typing.py", line 61, in test_extra_validator__issue_291
    self.assertEqual(result[2], 0, msg=result[1] or result[0])
AssertionError: 1 != 0 : xmlschema/xpath.py:308: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/xpath.py:48: error: Unused "type: ignore" comment
xmlschema/validators/wildcards.py:430: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/elements.py:392: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/assertions.py:165: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/schemas.py:559: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/schemas.py:565: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
Found 7 errors in 5 files (checked 1 source file)


======================================================================
FAIL: test_schema_source (tests.test_typing.TestTyping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$(BUILD_DIR)/tests/test_typing.py", line 44, in test_schema_source
    self.assertEqual(result[2], 0, msg=result[1] or result[0])
AssertionError: 1 != 0 : xmlschema/xpath.py:308: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/wildcards.py:430: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/elements.py:392: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/assertions.py:165: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/schemas.py:559: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/schemas.py:565: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
Found 6 errors in 5 files (checked 1 source file)


======================================================================
FAIL: test_simple_types (tests.test_typing.TestTyping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$(BUILD_DIR)/tests/test_typing.py", line 53, in test_simple_types
    self.assertEqual(result[2], 0, msg=result[1] or result[0])
AssertionError: 1 != 0 : xmlschema/xpath.py:308: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/wildcards.py:430: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/elements.py:392: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/assertions.py:165: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/schemas.py:559: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
xmlschema/validators/schemas.py:565: error: Redundant cast to "XMLSchemaBase"  [redundant-cast]
Found 6 errors in 5 files (checked 1 source file)
```
Please note that when I test with Python 3.9.16 all tests pass.

This is regression because for version 2.2.3 all tests pass with both Python 3.7.16 and Python 3.9.16.

**Comment by brunato** [comment]
I'll skip explicitly `test_typing.TestTyping` with Python 3.7 in the next bugfix release.
These tests are already skipped with Python 3.7 in _tox.ini_ an in CI tests.

Thank you for reporting this
