### ISSUE TITLE
XML validation against the XSD failed

### ISSUE THREAD

**Issue by AnujiVarghese** [sissaschool/xmlschema#349]
I prepared an XSD with the help of Altova XMLSpy and generated an XML file based on that XSD. It is valid in Altova XMLSpy. However, when I tried to validate it in the database using XMLSchema, it failed.

Sample XSD 

```xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2022 rel. 2 (x64) (http://www.altova.com) by AN-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:ra="http://www.test.com/ia/xml" xmlns:ns="2" targetNamespace="http://www.test.com/ia/xml" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="test">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="acquisition"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
```

Sample xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2022 rel. 2 (x64) (http://www.altova.com)-->
<ra:test xmlns:ra="http://www.test.com/ia/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.test.com/ia/xml 1.xsd">
	<ra:acquisition/>
</ra:test>
```

**Comment by brunato** [comment]
Hi,

maybe you have used the XSD 1.0 validator that create an empty schema (following the `vc:minVersion` rule):

```pycon
>>> import xmlschema
>>> schema = xmlschema.XMLSchema('issue_349.xsd')
>>> schema.validate('issue_349.xml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brunato/Development/xmlschema/xmlschema/validators/schemas.py", line 1703, in validate
    raise error
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating <Element '{http://www.test.com/ia/xml}test' at 0x7fd9207f0450> with XMLSchema10(name='issue_349.xsd', namespace='http://www.test.com/ia/xml'):

Reason: <Element '{http://www.test.com/ia/xml}test' at 0x7fd9207f0450> is not an element of the schema

Instance:

  <ra:test xmlns:ra="http://www.test.com/ia/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.test.com/ia/xml 1.xsd">
      <ra:acquisition />
  </ra:test>

Path: /ra:test

>>> 
```

using the XSD 1.1 validator this should work fine:

```pycon
>>> schema = xmlschema.XMLSchema11('issue_349.xsd')
>>> schema.validate('issue_349.xml')
>>> schema.is_valid('issue_349.xml')
True
```
```

**Comment by AnujiVarghese** [comment]
I have prepared an xsd using altova xmlspy. In that xsd, some elements expects string values and some elements expects integers. And these values should be entered in the xml against that elements. Otherwise that xml will be invalid against that xsd. If any of the values are missing, the xml will be invalid against that xsd. I used xmlschema library for validating the xsd and xml. 

```
CREATE OR REPLACE FUNCTION stateless_service_support.validate_rfp(xml_data xml, xsd_schema xml)
 RETURNS text
 LANGUAGE plpython3u
AS $function$
import xmlschema

try:
    xs = xmlschema.XMLSchema11(xsd_schema)
    xs.validate(xml_data)
    return True
except xmlschema.XMLSchemaValidationError as e:
    return str(e)
except Exception as e:
    return str(e)
$function$
;
```

I have prepared an XML against that XSD. But i haven't entered the string or integers that expected in xml elements. So this function shows the xml as invalid.
But, in my case if the integer values are missing need to show as valid. but if the strings missings need to show xml is invalid.
If there are 10 errors in the xml which makes xml invalid, i want to list all the erros in the xml. 
Can i do it with the xmlschema library? The above function returns only one error (the first error).

**Comment by brunato** [comment]
Use `list(xs.iter_errors(xml_data))` instead of `xs.validate(xml_data)`, e.g.:

```python
try:
    xs = xmlschema.XMLSchema11(xsd_schema)
    errors = list(xs.iter_errors(xml_data))
except Exception as e:
    return str(e)
else:
    if not errors:
        return True
    return '\n\n'.join(str(e) for e in errors)
```

**Comment by AnujiVarghese** [comment]
i tried the below query
```
CREATE OR REPLACE FUNCTION stateless_service_support.validate_rfp(xml_data xml, xsd_schema xml)
  RETURNS text
  LANGUAGE plpython3u
AS $function$
import xmlschema

try:
    xs = xmlschema.XMLSchema11(xsd_schema)
    errors = list(xs.iter_errors(xml_data))
except Exception as e:
    return str(e)
else:
    if not errors:
        return 'Validation successful'
    return '\n\n'.join(str(e) for e in errors)
$function$;
```
taking too much time to execute and failing the execution

**Comment by brunato** [comment]
If the XML data is big the time and memory used for validation could be high. There is also a _lazy_ option to reduce the memory used, but in this case the execution is a little slower.

To filter similar errors you can check exception (error) attributes/properties (e.g. _elem_ or _path_).

**Comment by AnujiVarghese** [comment]
Issue resolved. Thank you
