### ISSUE TITLE
v2.5.0 mamba installation fails

### ISSUE THREAD

**Issue by thawn** [sissaschool/xmlschema#370]
Trying to install xmlschema-2.5.0 with mamba fails with the following error

```
critical libmamba Pathname can't be converted from UTF-8 to current locale.
libmamba Error opening for reading "/minimamba/pkgs/xmlschema-2.5.0-pyhd8ed1ab_0/info/index.json": No such file or directory
```
my locale is en_US.UTF-8
OS: Ubuntu 20.04 (in a singularity container)

version 2.3.0 installed without errors in the same container.

<details>
<summary>full mamba error message</summary>
<pre>
critical libmamba Pathname can't be converted from UTF-8 to current locale.
error    libmamba Error opening for reading "/minimamba/pkgs/xmlschema-2.5.0-pyhd8ed1ab_0/info/index.json": No such file or directory
error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
xmlschema-2.5.0-pyhd8ed1ab_0.conda extraction failed
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "/minimamba/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/minimamba/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/minimamba/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 142, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/minimamba/lib/python3.9/site-packages/mamba/mamba_env.py", line 148, in mamba_install
        transaction.fetch_extract_packages()
    RuntimeError: Found incorrect download: xmlschema. Aborting
`$ /minimamba/bin//mamba create -p /app/env -f /environment.yml`
  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/minimamba
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
                     PATH=/minimamba/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbi
                          n:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
     active environment : None
       user config file : /root/.condarc
 populated config files : /minimamba/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __linux=5.10.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /minimamba  (writable)
      conda av data dir : /minimamba/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /minimamba/pkgs
                          /root/.conda/pkgs
       envs directories : /minimamba/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.13 Linux/5.10.0-23-amd64 ubuntu/20.04.6 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
</pre></details>

**Comment by brunato** [comment]
Hi,

seems to be a packaging issue for (mini)mamba (`info/index.json` is a missing file that not belongs to _xmlschema_ source package and i don't find a reason related to _xmlschema_ source in the error message). 

I'll try to reproduce in a similar installation but my advice is to report this also to _mamba_ maintainers.

**Comment by brunato** [comment]
This is not a bug of _xmlschema_, seems to be [libarchive (a C library used by mamba) that can't handle UFT-8 filenames](https://github.com/libarchive/libarchive/issues/587) if the locale is not set (`'C'`).

**Comment by brunato** [comment]
Trying installation on [miniforge3 docker images](https://hub.docker.com/r/condaforge/miniforge3) as described in [mamba documentation](https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html#docker-images): the installation issue seems to be resolved with release [23.11.0-0 of miniforge3](https://github.com/conda-forge/miniforge/releases/tag/23.11.0-0).
